// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 30 Mar 2018 12:26:20 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include <slurm/slurm.h>
#include "slurm_helpers.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

