// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// by https://git.io/c-for-go. DO NOT EDIT.

package slurm

/*
#cgo pkg-config: slurm
#include <slurm/slurm.h>
#include "slurm_helpers.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
)

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// allocJobDescMsgMemory allocates memory for type C.job_desc_msg_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocJobDescMsgMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfJobDescMsgValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfJobDescMsgValue = unsafe.Sizeof([1]C.job_desc_msg_t{})

type sliceHeader struct {
	Data uintptr
	Len  int
	Cap  int
}

// allocPCharMemory allocates memory for type *C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPCharValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfPCharValue = unsafe.Sizeof([1]*C.char{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackSSByte transforms a sliced Go data structure into plain C format.
func unpackSSByte(x [][]byte) (unpacked **C.char, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(&unpacked, func(***C.char) {
		go allocs.Free()
	})

	len0 := len(x)
	mem0 := allocPCharMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: uintptr(mem0),
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]*C.char)(unsafe.Pointer(h0))
	for i0 := range x {
		h := (*sliceHeader)(unsafe.Pointer(&x[i0]))
		v0[i0] = (*C.char)(unsafe.Pointer(h.Data))
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (**C.char)(unsafe.Pointer(h.Data))
	return
}

// packSSByte reads sliced Go data structure out from plain C format.
func packSSByte(v [][]byte, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		hxfa9955c := (*sliceHeader)(unsafe.Pointer(&v[i0]))
		hxfa9955c.Data = uintptr(unsafe.Pointer(ptr1))
		hxfa9955c.Cap = 0x7fffffff
		// hxfa9955c.Len = ?
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *JobDescMsg) Ref() *C.job_desc_msg_t {
	if x == nil {
		return nil
	}
	return x.ref1da77736
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *JobDescMsg) Free() {
	if x != nil && x.allocs1da77736 != nil {
		x.allocs1da77736.(*cgoAllocMap).Free()
		x.ref1da77736 = nil
	}
}

// NewJobDescMsgRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewJobDescMsgRef(ref unsafe.Pointer) *JobDescMsg {
	if ref == nil {
		return nil
	}
	obj := new(JobDescMsg)
	obj.ref1da77736 = (*C.job_desc_msg_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *JobDescMsg) PassRef() (*C.job_desc_msg_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref1da77736 != nil {
		return x.ref1da77736, nil
	}
	mem1da77736 := allocJobDescMsgMemory(1)
	ref1da77736 := (*C.job_desc_msg_t)(mem1da77736)
	allocs1da77736 := new(cgoAllocMap)
	allocs1da77736.Add(mem1da77736)

	var caccount_allocs *cgoAllocMap
	ref1da77736.account, caccount_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Account)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(caccount_allocs)

	var cacctg_freq_allocs *cgoAllocMap
	ref1da77736.acctg_freq, cacctg_freq_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.AcctgFreq)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cacctg_freq_allocs)

	var cadmin_comment_allocs *cgoAllocMap
	ref1da77736.admin_comment, cadmin_comment_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.AdminComment)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cadmin_comment_allocs)

	var calloc_node_allocs *cgoAllocMap
	ref1da77736.alloc_node, calloc_node_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.AllocNode)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(calloc_node_allocs)

	var calloc_resp_port_allocs *cgoAllocMap
	ref1da77736.alloc_resp_port, calloc_resp_port_allocs = (C.uint16_t)(x.AllocRespPort), cgoAllocsUnknown
	allocs1da77736.Borrow(calloc_resp_port_allocs)

	var calloc_sid_allocs *cgoAllocMap
	ref1da77736.alloc_sid, calloc_sid_allocs = (C.uint32_t)(x.AllocSid), cgoAllocsUnknown
	allocs1da77736.Borrow(calloc_sid_allocs)

	var cargc_allocs *cgoAllocMap
	ref1da77736.argc, cargc_allocs = (C.uint32_t)(x.Argc), cgoAllocsUnknown
	allocs1da77736.Borrow(cargc_allocs)

	var cargv_allocs *cgoAllocMap
	ref1da77736.argv, cargv_allocs = unpackSSByte(x.Argv)
	allocs1da77736.Borrow(cargv_allocs)

	var carray_inx_allocs *cgoAllocMap
	ref1da77736.array_inx, carray_inx_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ArrayInx)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(carray_inx_allocs)

	var carray_bitmap_allocs *cgoAllocMap
	ref1da77736.array_bitmap, carray_bitmap_allocs = *(*unsafe.Pointer)(unsafe.Pointer(&x.ArrayBitmap)), cgoAllocsUnknown
	allocs1da77736.Borrow(carray_bitmap_allocs)

	var cbegin_time_allocs *cgoAllocMap
	ref1da77736.begin_time, cbegin_time_allocs = (C.time_t)(x.BeginTime), cgoAllocsUnknown
	allocs1da77736.Borrow(cbegin_time_allocs)

	var cbitflags_allocs *cgoAllocMap
	ref1da77736.bitflags, cbitflags_allocs = (C.uint32_t)(x.Bitflags), cgoAllocsUnknown
	allocs1da77736.Borrow(cbitflags_allocs)

	var cburst_buffer_allocs *cgoAllocMap
	ref1da77736.burst_buffer, cburst_buffer_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.BurstBuffer)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cburst_buffer_allocs)

	var cckpt_interval_allocs *cgoAllocMap
	ref1da77736.ckpt_interval, cckpt_interval_allocs = (C.uint16_t)(x.CkptInterval), cgoAllocsUnknown
	allocs1da77736.Borrow(cckpt_interval_allocs)

	var cckpt_dir_allocs *cgoAllocMap
	ref1da77736.ckpt_dir, cckpt_dir_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.CkptDir)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cckpt_dir_allocs)

	var cclusters_allocs *cgoAllocMap
	ref1da77736.clusters, cclusters_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Clusters)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cclusters_allocs)

	var ccluster_features_allocs *cgoAllocMap
	ref1da77736.cluster_features, ccluster_features_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ClusterFeatures)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(ccluster_features_allocs)

	var ccomment_allocs *cgoAllocMap
	ref1da77736.comment, ccomment_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Comment)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(ccomment_allocs)

	var ccontiguous_allocs *cgoAllocMap
	ref1da77736.contiguous, ccontiguous_allocs = (C.uint16_t)(x.Contiguous), cgoAllocsUnknown
	allocs1da77736.Borrow(ccontiguous_allocs)

	var ccore_spec_allocs *cgoAllocMap
	ref1da77736.core_spec, ccore_spec_allocs = (C.uint16_t)(x.CoreSpec), cgoAllocsUnknown
	allocs1da77736.Borrow(ccore_spec_allocs)

	var ccpu_bind_allocs *cgoAllocMap
	ref1da77736.cpu_bind, ccpu_bind_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.CpuBind)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpu_bind_allocs)

	var ccpu_bind_type_allocs *cgoAllocMap
	ref1da77736.cpu_bind_type, ccpu_bind_type_allocs = (C.uint16_t)(x.CpuBindType), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpu_bind_type_allocs)

	var ccpu_freq_min_allocs *cgoAllocMap
	ref1da77736.cpu_freq_min, ccpu_freq_min_allocs = (C.uint32_t)(x.CpuFreqMin), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpu_freq_min_allocs)

	var ccpu_freq_max_allocs *cgoAllocMap
	ref1da77736.cpu_freq_max, ccpu_freq_max_allocs = (C.uint32_t)(x.CpuFreqMax), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpu_freq_max_allocs)

	var ccpu_freq_gov_allocs *cgoAllocMap
	ref1da77736.cpu_freq_gov, ccpu_freq_gov_allocs = (C.uint32_t)(x.CpuFreqGov), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpu_freq_gov_allocs)

	var cdeadline_allocs *cgoAllocMap
	ref1da77736.deadline, cdeadline_allocs = (C.time_t)(x.Deadline), cgoAllocsUnknown
	allocs1da77736.Borrow(cdeadline_allocs)

	var cdelay_boot_allocs *cgoAllocMap
	ref1da77736.delay_boot, cdelay_boot_allocs = (C.uint32_t)(x.DelayBoot), cgoAllocsUnknown
	allocs1da77736.Borrow(cdelay_boot_allocs)

	var cdependency_allocs *cgoAllocMap
	ref1da77736.dependency, cdependency_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Dependency)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cdependency_allocs)

	var cend_time_allocs *cgoAllocMap
	ref1da77736.end_time, cend_time_allocs = (C.time_t)(x.EndTime), cgoAllocsUnknown
	allocs1da77736.Borrow(cend_time_allocs)

	var cenvironment_allocs *cgoAllocMap
	ref1da77736.environment, cenvironment_allocs = unpackSSByte(x.Environment)
	allocs1da77736.Borrow(cenvironment_allocs)

	var cenv_size_allocs *cgoAllocMap
	ref1da77736.env_size, cenv_size_allocs = (C.uint32_t)(x.EnvSize), cgoAllocsUnknown
	allocs1da77736.Borrow(cenv_size_allocs)

	var cextra_allocs *cgoAllocMap
	ref1da77736.extra, cextra_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Extra)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cextra_allocs)

	var cexc_nodes_allocs *cgoAllocMap
	ref1da77736.exc_nodes, cexc_nodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ExcNodes)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cexc_nodes_allocs)

	var cfeatures_allocs *cgoAllocMap
	ref1da77736.features, cfeatures_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Features)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cfeatures_allocs)

	var cfed_siblings_active_allocs *cgoAllocMap
	ref1da77736.fed_siblings_active, cfed_siblings_active_allocs = (C.uint64_t)(x.FedSiblingsActive), cgoAllocsUnknown
	allocs1da77736.Borrow(cfed_siblings_active_allocs)

	var cfed_siblings_viable_allocs *cgoAllocMap
	ref1da77736.fed_siblings_viable, cfed_siblings_viable_allocs = (C.uint64_t)(x.FedSiblingsViable), cgoAllocsUnknown
	allocs1da77736.Borrow(cfed_siblings_viable_allocs)

	var cgres_allocs *cgoAllocMap
	ref1da77736.gres, cgres_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Gres)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cgres_allocs)

	var cgroup_id_allocs *cgoAllocMap
	ref1da77736.group_id, cgroup_id_allocs = (C.uint32_t)(x.GroupId), cgoAllocsUnknown
	allocs1da77736.Borrow(cgroup_id_allocs)

	var cimmediate_allocs *cgoAllocMap
	ref1da77736.immediate, cimmediate_allocs = (C.uint16_t)(x.Immediate), cgoAllocsUnknown
	allocs1da77736.Borrow(cimmediate_allocs)

	var cjob_id_allocs *cgoAllocMap
	ref1da77736.job_id, cjob_id_allocs = (C.uint32_t)(x.JobId), cgoAllocsUnknown
	allocs1da77736.Borrow(cjob_id_allocs)

	var cjob_id_str_allocs *cgoAllocMap
	ref1da77736.job_id_str, cjob_id_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.JobIdStr)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cjob_id_str_allocs)

	var ckill_on_node_fail_allocs *cgoAllocMap
	ref1da77736.kill_on_node_fail, ckill_on_node_fail_allocs = (C.uint16_t)(x.KillOnNodeFail), cgoAllocsUnknown
	allocs1da77736.Borrow(ckill_on_node_fail_allocs)

	var clicenses_allocs *cgoAllocMap
	ref1da77736.licenses, clicenses_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Licenses)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(clicenses_allocs)

	var cmail_type_allocs *cgoAllocMap
	ref1da77736.mail_type, cmail_type_allocs = (C.uint16_t)(x.MailType), cgoAllocsUnknown
	allocs1da77736.Borrow(cmail_type_allocs)

	var cmail_user_allocs *cgoAllocMap
	ref1da77736.mail_user, cmail_user_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.MailUser)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cmail_user_allocs)

	var cmcs_label_allocs *cgoAllocMap
	ref1da77736.mcs_label, cmcs_label_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.McsLabel)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cmcs_label_allocs)

	var cmem_bind_allocs *cgoAllocMap
	ref1da77736.mem_bind, cmem_bind_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.MemBind)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cmem_bind_allocs)

	var cmem_bind_type_allocs *cgoAllocMap
	ref1da77736.mem_bind_type, cmem_bind_type_allocs = (C.uint16_t)(x.MemBindType), cgoAllocsUnknown
	allocs1da77736.Borrow(cmem_bind_type_allocs)

	var cname_allocs *cgoAllocMap
	ref1da77736.name, cname_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Name)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cname_allocs)

	var cnetwork_allocs *cgoAllocMap
	ref1da77736.network, cnetwork_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Network)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cnetwork_allocs)

	var cnice_allocs *cgoAllocMap
	ref1da77736.nice, cnice_allocs = (C.uint32_t)(x.Nice), cgoAllocsUnknown
	allocs1da77736.Borrow(cnice_allocs)

	var cnum_tasks_allocs *cgoAllocMap
	ref1da77736.num_tasks, cnum_tasks_allocs = (C.uint32_t)(x.NumTasks), cgoAllocsUnknown
	allocs1da77736.Borrow(cnum_tasks_allocs)

	var copen_mode_allocs *cgoAllocMap
	ref1da77736.open_mode, copen_mode_allocs = (C.uint8_t)(x.OpenMode), cgoAllocsUnknown
	allocs1da77736.Borrow(copen_mode_allocs)

	var corigin_cluster_allocs *cgoAllocMap
	ref1da77736.origin_cluster, corigin_cluster_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.OriginCluster)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(corigin_cluster_allocs)

	var cother_port_allocs *cgoAllocMap
	ref1da77736.other_port, cother_port_allocs = (C.uint16_t)(x.OtherPort), cgoAllocsUnknown
	allocs1da77736.Borrow(cother_port_allocs)

	var covercommit_allocs *cgoAllocMap
	ref1da77736.overcommit, covercommit_allocs = (C.uint8_t)(x.Overcommit), cgoAllocsUnknown
	allocs1da77736.Borrow(covercommit_allocs)

	var cpack_job_offset_allocs *cgoAllocMap
	ref1da77736.pack_job_offset, cpack_job_offset_allocs = (C.uint32_t)(x.PackJobOffset), cgoAllocsUnknown
	allocs1da77736.Borrow(cpack_job_offset_allocs)

	var cpartition_allocs *cgoAllocMap
	ref1da77736.partition, cpartition_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Partition)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cpartition_allocs)

	var cplane_size_allocs *cgoAllocMap
	ref1da77736.plane_size, cplane_size_allocs = (C.uint16_t)(x.PlaneSize), cgoAllocsUnknown
	allocs1da77736.Borrow(cplane_size_allocs)

	var cpower_flags_allocs *cgoAllocMap
	ref1da77736.power_flags, cpower_flags_allocs = (C.uint8_t)(x.PowerFlags), cgoAllocsUnknown
	allocs1da77736.Borrow(cpower_flags_allocs)

	var cpriority_allocs *cgoAllocMap
	ref1da77736.priority, cpriority_allocs = (C.uint32_t)(x.Priority), cgoAllocsUnknown
	allocs1da77736.Borrow(cpriority_allocs)

	var cprofile_allocs *cgoAllocMap
	ref1da77736.profile, cprofile_allocs = (C.uint32_t)(x.Profile), cgoAllocsUnknown
	allocs1da77736.Borrow(cprofile_allocs)

	var cqos_allocs *cgoAllocMap
	ref1da77736.qos, cqos_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Qos)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cqos_allocs)

	var creboot_allocs *cgoAllocMap
	ref1da77736.reboot, creboot_allocs = (C.uint16_t)(x.Reboot), cgoAllocsUnknown
	allocs1da77736.Borrow(creboot_allocs)

	var cresp_host_allocs *cgoAllocMap
	ref1da77736.resp_host, cresp_host_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.RespHost)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cresp_host_allocs)

	var crestart_cnt_allocs *cgoAllocMap
	ref1da77736.restart_cnt, crestart_cnt_allocs = (C.uint16_t)(x.RestartCnt), cgoAllocsUnknown
	allocs1da77736.Borrow(crestart_cnt_allocs)

	var creq_nodes_allocs *cgoAllocMap
	ref1da77736.req_nodes, creq_nodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ReqNodes)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(creq_nodes_allocs)

	var crequeue_allocs *cgoAllocMap
	ref1da77736.requeue, crequeue_allocs = (C.uint16_t)(x.Requeue), cgoAllocsUnknown
	allocs1da77736.Borrow(crequeue_allocs)

	var creservation_allocs *cgoAllocMap
	ref1da77736.reservation, creservation_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Reservation)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(creservation_allocs)

	var cscript_allocs *cgoAllocMap
	ref1da77736.script, cscript_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Script)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cscript_allocs)

	var cshared_allocs *cgoAllocMap
	ref1da77736.shared, cshared_allocs = (C.uint16_t)(x.Shared), cgoAllocsUnknown
	allocs1da77736.Borrow(cshared_allocs)

	var cspank_job_env_allocs *cgoAllocMap
	ref1da77736.spank_job_env, cspank_job_env_allocs = unpackSSByte(x.SpankJobEnv)
	allocs1da77736.Borrow(cspank_job_env_allocs)

	var cspank_job_env_size_allocs *cgoAllocMap
	ref1da77736.spank_job_env_size, cspank_job_env_size_allocs = (C.uint32_t)(x.SpankJobEnvSize), cgoAllocsUnknown
	allocs1da77736.Borrow(cspank_job_env_size_allocs)

	var ctask_dist_allocs *cgoAllocMap
	ref1da77736.task_dist, ctask_dist_allocs = (C.uint32_t)(x.TaskDist), cgoAllocsUnknown
	allocs1da77736.Borrow(ctask_dist_allocs)

	var ctime_limit_allocs *cgoAllocMap
	ref1da77736.time_limit, ctime_limit_allocs = (C.uint32_t)(x.TimeLimit), cgoAllocsUnknown
	allocs1da77736.Borrow(ctime_limit_allocs)

	var ctime_min_allocs *cgoAllocMap
	ref1da77736.time_min, ctime_min_allocs = (C.uint32_t)(x.TimeMin), cgoAllocsUnknown
	allocs1da77736.Borrow(ctime_min_allocs)

	var cuser_id_allocs *cgoAllocMap
	ref1da77736.user_id, cuser_id_allocs = (C.uint32_t)(x.UserId), cgoAllocsUnknown
	allocs1da77736.Borrow(cuser_id_allocs)

	var cwait_all_nodes_allocs *cgoAllocMap
	ref1da77736.wait_all_nodes, cwait_all_nodes_allocs = (C.uint16_t)(x.WaitAllNodes), cgoAllocsUnknown
	allocs1da77736.Borrow(cwait_all_nodes_allocs)

	var cwarn_flags_allocs *cgoAllocMap
	ref1da77736.warn_flags, cwarn_flags_allocs = (C.uint16_t)(x.WarnFlags), cgoAllocsUnknown
	allocs1da77736.Borrow(cwarn_flags_allocs)

	var cwarn_signal_allocs *cgoAllocMap
	ref1da77736.warn_signal, cwarn_signal_allocs = (C.uint16_t)(x.WarnSignal), cgoAllocsUnknown
	allocs1da77736.Borrow(cwarn_signal_allocs)

	var cwarn_time_allocs *cgoAllocMap
	ref1da77736.warn_time, cwarn_time_allocs = (C.uint16_t)(x.WarnTime), cgoAllocsUnknown
	allocs1da77736.Borrow(cwarn_time_allocs)

	var cwork_dir_allocs *cgoAllocMap
	ref1da77736.work_dir, cwork_dir_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.WorkDir)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cwork_dir_allocs)

	var ccpus_per_task_allocs *cgoAllocMap
	ref1da77736.cpus_per_task, ccpus_per_task_allocs = (C.uint16_t)(x.CpusPerTask), cgoAllocsUnknown
	allocs1da77736.Borrow(ccpus_per_task_allocs)

	var cmin_cpus_allocs *cgoAllocMap
	ref1da77736.min_cpus, cmin_cpus_allocs = (C.uint32_t)(x.MinCpus), cgoAllocsUnknown
	allocs1da77736.Borrow(cmin_cpus_allocs)

	var cmax_cpus_allocs *cgoAllocMap
	ref1da77736.max_cpus, cmax_cpus_allocs = (C.uint32_t)(x.MaxCpus), cgoAllocsUnknown
	allocs1da77736.Borrow(cmax_cpus_allocs)

	var cmin_nodes_allocs *cgoAllocMap
	ref1da77736.min_nodes, cmin_nodes_allocs = (C.uint32_t)(x.MinNodes), cgoAllocsUnknown
	allocs1da77736.Borrow(cmin_nodes_allocs)

	var cmax_nodes_allocs *cgoAllocMap
	ref1da77736.max_nodes, cmax_nodes_allocs = (C.uint32_t)(x.MaxNodes), cgoAllocsUnknown
	allocs1da77736.Borrow(cmax_nodes_allocs)

	var cboards_per_node_allocs *cgoAllocMap
	ref1da77736.boards_per_node, cboards_per_node_allocs = (C.uint16_t)(x.BoardsPerNode), cgoAllocsUnknown
	allocs1da77736.Borrow(cboards_per_node_allocs)

	var csockets_per_board_allocs *cgoAllocMap
	ref1da77736.sockets_per_board, csockets_per_board_allocs = (C.uint16_t)(x.SocketsPerBoard), cgoAllocsUnknown
	allocs1da77736.Borrow(csockets_per_board_allocs)

	var csockets_per_node_allocs *cgoAllocMap
	ref1da77736.sockets_per_node, csockets_per_node_allocs = (C.uint16_t)(x.SocketsPerNode), cgoAllocsUnknown
	allocs1da77736.Borrow(csockets_per_node_allocs)

	var ccores_per_socket_allocs *cgoAllocMap
	ref1da77736.cores_per_socket, ccores_per_socket_allocs = (C.uint16_t)(x.CoresPerSocket), cgoAllocsUnknown
	allocs1da77736.Borrow(ccores_per_socket_allocs)

	var cthreads_per_core_allocs *cgoAllocMap
	ref1da77736.threads_per_core, cthreads_per_core_allocs = (C.uint16_t)(x.ThreadsPerCore), cgoAllocsUnknown
	allocs1da77736.Borrow(cthreads_per_core_allocs)

	var cntasks_per_node_allocs *cgoAllocMap
	ref1da77736.ntasks_per_node, cntasks_per_node_allocs = (C.uint16_t)(x.NtasksPerNode), cgoAllocsUnknown
	allocs1da77736.Borrow(cntasks_per_node_allocs)

	var cntasks_per_socket_allocs *cgoAllocMap
	ref1da77736.ntasks_per_socket, cntasks_per_socket_allocs = (C.uint16_t)(x.NtasksPerSocket), cgoAllocsUnknown
	allocs1da77736.Borrow(cntasks_per_socket_allocs)

	var cntasks_per_core_allocs *cgoAllocMap
	ref1da77736.ntasks_per_core, cntasks_per_core_allocs = (C.uint16_t)(x.NtasksPerCore), cgoAllocsUnknown
	allocs1da77736.Borrow(cntasks_per_core_allocs)

	var cntasks_per_board_allocs *cgoAllocMap
	ref1da77736.ntasks_per_board, cntasks_per_board_allocs = (C.uint16_t)(x.NtasksPerBoard), cgoAllocsUnknown
	allocs1da77736.Borrow(cntasks_per_board_allocs)

	var cpn_min_cpus_allocs *cgoAllocMap
	ref1da77736.pn_min_cpus, cpn_min_cpus_allocs = (C.uint16_t)(x.PnMinCpus), cgoAllocsUnknown
	allocs1da77736.Borrow(cpn_min_cpus_allocs)

	var cpn_min_memory_allocs *cgoAllocMap
	ref1da77736.pn_min_memory, cpn_min_memory_allocs = (C.uint64_t)(x.PnMinMemory), cgoAllocsUnknown
	allocs1da77736.Borrow(cpn_min_memory_allocs)

	var cpn_min_tmp_disk_allocs *cgoAllocMap
	ref1da77736.pn_min_tmp_disk, cpn_min_tmp_disk_allocs = (C.uint32_t)(x.PnMinTmpDisk), cgoAllocsUnknown
	allocs1da77736.Borrow(cpn_min_tmp_disk_allocs)

	var cgeometry_allocs *cgoAllocMap
	ref1da77736.geometry, cgeometry_allocs = *(*[5]C.uint16_t)(unsafe.Pointer(&x.Geometry)), cgoAllocsUnknown
	allocs1da77736.Borrow(cgeometry_allocs)

	var cconn_type_allocs *cgoAllocMap
	ref1da77736.conn_type, cconn_type_allocs = *(*[5]C.uint16_t)(unsafe.Pointer(&x.ConnType)), cgoAllocsUnknown
	allocs1da77736.Borrow(cconn_type_allocs)

	var crotate_allocs *cgoAllocMap
	ref1da77736.rotate, crotate_allocs = (C.uint16_t)(x.Rotate), cgoAllocsUnknown
	allocs1da77736.Borrow(crotate_allocs)

	var cblrtsimage_allocs *cgoAllocMap
	ref1da77736.blrtsimage, cblrtsimage_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Blrtsimage)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cblrtsimage_allocs)

	var clinuximage_allocs *cgoAllocMap
	ref1da77736.linuximage, clinuximage_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Linuximage)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(clinuximage_allocs)

	var cmloaderimage_allocs *cgoAllocMap
	ref1da77736.mloaderimage, cmloaderimage_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Mloaderimage)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cmloaderimage_allocs)

	var cramdiskimage_allocs *cgoAllocMap
	ref1da77736.ramdiskimage, cramdiskimage_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Ramdiskimage)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cramdiskimage_allocs)

	var creq_switch_allocs *cgoAllocMap
	ref1da77736.req_switch, creq_switch_allocs = (C.uint32_t)(x.ReqSwitch), cgoAllocsUnknown
	allocs1da77736.Borrow(creq_switch_allocs)

	var cstd_err_allocs *cgoAllocMap
	ref1da77736.std_err, cstd_err_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdErr)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cstd_err_allocs)

	var cstd_in_allocs *cgoAllocMap
	ref1da77736.std_in, cstd_in_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdIn)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cstd_in_allocs)

	var cstd_out_allocs *cgoAllocMap
	ref1da77736.std_out, cstd_out_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdOut)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cstd_out_allocs)

	var ctres_req_cnt_allocs *cgoAllocMap
	ref1da77736.tres_req_cnt, ctres_req_cnt_allocs = (*C.uint64_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.TresReqCnt)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(ctres_req_cnt_allocs)

	var cwait4switch_allocs *cgoAllocMap
	ref1da77736.wait4switch, cwait4switch_allocs = (C.uint32_t)(x.Wait4switch), cgoAllocsUnknown
	allocs1da77736.Borrow(cwait4switch_allocs)

	var cwckey_allocs *cgoAllocMap
	ref1da77736.wckey, cwckey_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Wckey)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cwckey_allocs)

	var cx11_allocs *cgoAllocMap
	ref1da77736.x11, cx11_allocs = (C.uint16_t)(x.X11), cgoAllocsUnknown
	allocs1da77736.Borrow(cx11_allocs)

	var cx11_magic_cookie_allocs *cgoAllocMap
	ref1da77736.x11_magic_cookie, cx11_magic_cookie_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.X11MagicCookie)).Data)), cgoAllocsUnknown
	allocs1da77736.Borrow(cx11_magic_cookie_allocs)

	var cx11_target_port_allocs *cgoAllocMap
	ref1da77736.x11_target_port, cx11_target_port_allocs = (C.uint16_t)(x.X11TargetPort), cgoAllocsUnknown
	allocs1da77736.Borrow(cx11_target_port_allocs)

	x.ref1da77736 = ref1da77736
	x.allocs1da77736 = allocs1da77736
	return ref1da77736, allocs1da77736

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x JobDescMsg) PassValue() (C.job_desc_msg_t, *cgoAllocMap) {
	if x.ref1da77736 != nil {
		return *x.ref1da77736, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *JobDescMsg) Deref() {
	if x.ref1da77736 == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Account))
	hxfc4425b.Data = uintptr(unsafe.Pointer(x.ref1da77736.account))
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ?

	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.AcctgFreq))
	hxf95e7c8.Data = uintptr(unsafe.Pointer(x.ref1da77736.acctg_freq))
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ?

	hxff2234b := (*sliceHeader)(unsafe.Pointer(&x.AdminComment))
	hxff2234b.Data = uintptr(unsafe.Pointer(x.ref1da77736.admin_comment))
	hxff2234b.Cap = 0x7fffffff
	// hxff2234b.Len = ?

	hxff73280 := (*sliceHeader)(unsafe.Pointer(&x.AllocNode))
	hxff73280.Data = uintptr(unsafe.Pointer(x.ref1da77736.alloc_node))
	hxff73280.Cap = 0x7fffffff
	// hxff73280.Len = ?

	x.AllocRespPort = (uint16)(x.ref1da77736.alloc_resp_port)
	x.AllocSid = (uint32)(x.ref1da77736.alloc_sid)
	x.Argc = (uint32)(x.ref1da77736.argc)
	packSSByte(x.Argv, x.ref1da77736.argv)
	hxfa3f05c := (*sliceHeader)(unsafe.Pointer(&x.ArrayInx))
	hxfa3f05c.Data = uintptr(unsafe.Pointer(x.ref1da77736.array_inx))
	hxfa3f05c.Cap = 0x7fffffff
	// hxfa3f05c.Len = ?

	x.ArrayBitmap = (unsafe.Pointer)(unsafe.Pointer(x.ref1da77736.array_bitmap))
	x.BeginTime = (int)(x.ref1da77736.begin_time)
	x.Bitflags = (uint32)(x.ref1da77736.bitflags)
	hxf0d18b7 := (*sliceHeader)(unsafe.Pointer(&x.BurstBuffer))
	hxf0d18b7.Data = uintptr(unsafe.Pointer(x.ref1da77736.burst_buffer))
	hxf0d18b7.Cap = 0x7fffffff
	// hxf0d18b7.Len = ?

	x.CkptInterval = (uint16)(x.ref1da77736.ckpt_interval)
	hxf2fab0d := (*sliceHeader)(unsafe.Pointer(&x.CkptDir))
	hxf2fab0d.Data = uintptr(unsafe.Pointer(x.ref1da77736.ckpt_dir))
	hxf2fab0d.Cap = 0x7fffffff
	// hxf2fab0d.Len = ?

	hxf69fe70 := (*sliceHeader)(unsafe.Pointer(&x.Clusters))
	hxf69fe70.Data = uintptr(unsafe.Pointer(x.ref1da77736.clusters))
	hxf69fe70.Cap = 0x7fffffff
	// hxf69fe70.Len = ?

	hxf65bf54 := (*sliceHeader)(unsafe.Pointer(&x.ClusterFeatures))
	hxf65bf54.Data = uintptr(unsafe.Pointer(x.ref1da77736.cluster_features))
	hxf65bf54.Cap = 0x7fffffff
	// hxf65bf54.Len = ?

	hxf3b8dbd := (*sliceHeader)(unsafe.Pointer(&x.Comment))
	hxf3b8dbd.Data = uintptr(unsafe.Pointer(x.ref1da77736.comment))
	hxf3b8dbd.Cap = 0x7fffffff
	// hxf3b8dbd.Len = ?

	x.Contiguous = (uint16)(x.ref1da77736.contiguous)
	x.CoreSpec = (uint16)(x.ref1da77736.core_spec)
	hxf7a6dff := (*sliceHeader)(unsafe.Pointer(&x.CpuBind))
	hxf7a6dff.Data = uintptr(unsafe.Pointer(x.ref1da77736.cpu_bind))
	hxf7a6dff.Cap = 0x7fffffff
	// hxf7a6dff.Len = ?

	x.CpuBindType = (uint16)(x.ref1da77736.cpu_bind_type)
	x.CpuFreqMin = (uint32)(x.ref1da77736.cpu_freq_min)
	x.CpuFreqMax = (uint32)(x.ref1da77736.cpu_freq_max)
	x.CpuFreqGov = (uint32)(x.ref1da77736.cpu_freq_gov)
	x.Deadline = (int)(x.ref1da77736.deadline)
	x.DelayBoot = (uint32)(x.ref1da77736.delay_boot)
	hxfe48d67 := (*sliceHeader)(unsafe.Pointer(&x.Dependency))
	hxfe48d67.Data = uintptr(unsafe.Pointer(x.ref1da77736.dependency))
	hxfe48d67.Cap = 0x7fffffff
	// hxfe48d67.Len = ?

	x.EndTime = (int)(x.ref1da77736.end_time)
	packSSByte(x.Environment, x.ref1da77736.environment)
	x.EnvSize = (uint32)(x.ref1da77736.env_size)
	hxf058b18 := (*sliceHeader)(unsafe.Pointer(&x.Extra))
	hxf058b18.Data = uintptr(unsafe.Pointer(x.ref1da77736.extra))
	hxf058b18.Cap = 0x7fffffff
	// hxf058b18.Len = ?

	hxff6bc57 := (*sliceHeader)(unsafe.Pointer(&x.ExcNodes))
	hxff6bc57.Data = uintptr(unsafe.Pointer(x.ref1da77736.exc_nodes))
	hxff6bc57.Cap = 0x7fffffff
	// hxff6bc57.Len = ?

	hxf5fa529 := (*sliceHeader)(unsafe.Pointer(&x.Features))
	hxf5fa529.Data = uintptr(unsafe.Pointer(x.ref1da77736.features))
	hxf5fa529.Cap = 0x7fffffff
	// hxf5fa529.Len = ?

	x.FedSiblingsActive = (uint)(x.ref1da77736.fed_siblings_active)
	x.FedSiblingsViable = (uint)(x.ref1da77736.fed_siblings_viable)
	hxf21690b := (*sliceHeader)(unsafe.Pointer(&x.Gres))
	hxf21690b.Data = uintptr(unsafe.Pointer(x.ref1da77736.gres))
	hxf21690b.Cap = 0x7fffffff
	// hxf21690b.Len = ?

	x.GroupId = (uint32)(x.ref1da77736.group_id)
	x.Immediate = (uint16)(x.ref1da77736.immediate)
	x.JobId = (uint32)(x.ref1da77736.job_id)
	hxf1231c9 := (*sliceHeader)(unsafe.Pointer(&x.JobIdStr))
	hxf1231c9.Data = uintptr(unsafe.Pointer(x.ref1da77736.job_id_str))
	hxf1231c9.Cap = 0x7fffffff
	// hxf1231c9.Len = ?

	x.KillOnNodeFail = (uint16)(x.ref1da77736.kill_on_node_fail)
	hxf04b15b := (*sliceHeader)(unsafe.Pointer(&x.Licenses))
	hxf04b15b.Data = uintptr(unsafe.Pointer(x.ref1da77736.licenses))
	hxf04b15b.Cap = 0x7fffffff
	// hxf04b15b.Len = ?

	x.MailType = (uint16)(x.ref1da77736.mail_type)
	hxf2f888b := (*sliceHeader)(unsafe.Pointer(&x.MailUser))
	hxf2f888b.Data = uintptr(unsafe.Pointer(x.ref1da77736.mail_user))
	hxf2f888b.Cap = 0x7fffffff
	// hxf2f888b.Len = ?

	hxf5d1de2 := (*sliceHeader)(unsafe.Pointer(&x.McsLabel))
	hxf5d1de2.Data = uintptr(unsafe.Pointer(x.ref1da77736.mcs_label))
	hxf5d1de2.Cap = 0x7fffffff
	// hxf5d1de2.Len = ?

	hxfe53d34 := (*sliceHeader)(unsafe.Pointer(&x.MemBind))
	hxfe53d34.Data = uintptr(unsafe.Pointer(x.ref1da77736.mem_bind))
	hxfe53d34.Cap = 0x7fffffff
	// hxfe53d34.Len = ?

	x.MemBindType = (uint16)(x.ref1da77736.mem_bind_type)
	hxf547023 := (*sliceHeader)(unsafe.Pointer(&x.Name))
	hxf547023.Data = uintptr(unsafe.Pointer(x.ref1da77736.name))
	hxf547023.Cap = 0x7fffffff
	// hxf547023.Len = ?

	hxf5ebb88 := (*sliceHeader)(unsafe.Pointer(&x.Network))
	hxf5ebb88.Data = uintptr(unsafe.Pointer(x.ref1da77736.network))
	hxf5ebb88.Cap = 0x7fffffff
	// hxf5ebb88.Len = ?

	x.Nice = (uint32)(x.ref1da77736.nice)
	x.NumTasks = (uint32)(x.ref1da77736.num_tasks)
	x.OpenMode = (byte)(x.ref1da77736.open_mode)
	hxff20e84 := (*sliceHeader)(unsafe.Pointer(&x.OriginCluster))
	hxff20e84.Data = uintptr(unsafe.Pointer(x.ref1da77736.origin_cluster))
	hxff20e84.Cap = 0x7fffffff
	// hxff20e84.Len = ?

	x.OtherPort = (uint16)(x.ref1da77736.other_port)
	x.Overcommit = (byte)(x.ref1da77736.overcommit)
	x.PackJobOffset = (uint32)(x.ref1da77736.pack_job_offset)
	hxfa26a4d := (*sliceHeader)(unsafe.Pointer(&x.Partition))
	hxfa26a4d.Data = uintptr(unsafe.Pointer(x.ref1da77736.partition))
	hxfa26a4d.Cap = 0x7fffffff
	// hxfa26a4d.Len = ?

	x.PlaneSize = (uint16)(x.ref1da77736.plane_size)
	x.PowerFlags = (byte)(x.ref1da77736.power_flags)
	x.Priority = (uint32)(x.ref1da77736.priority)
	x.Profile = (uint32)(x.ref1da77736.profile)
	hxfe48098 := (*sliceHeader)(unsafe.Pointer(&x.Qos))
	hxfe48098.Data = uintptr(unsafe.Pointer(x.ref1da77736.qos))
	hxfe48098.Cap = 0x7fffffff
	// hxfe48098.Len = ?

	x.Reboot = (uint16)(x.ref1da77736.reboot)
	hxffe3496 := (*sliceHeader)(unsafe.Pointer(&x.RespHost))
	hxffe3496.Data = uintptr(unsafe.Pointer(x.ref1da77736.resp_host))
	hxffe3496.Cap = 0x7fffffff
	// hxffe3496.Len = ?

	x.RestartCnt = (uint16)(x.ref1da77736.restart_cnt)
	hxf5d48a6 := (*sliceHeader)(unsafe.Pointer(&x.ReqNodes))
	hxf5d48a6.Data = uintptr(unsafe.Pointer(x.ref1da77736.req_nodes))
	hxf5d48a6.Cap = 0x7fffffff
	// hxf5d48a6.Len = ?

	x.Requeue = (uint16)(x.ref1da77736.requeue)
	hxf685469 := (*sliceHeader)(unsafe.Pointer(&x.Reservation))
	hxf685469.Data = uintptr(unsafe.Pointer(x.ref1da77736.reservation))
	hxf685469.Cap = 0x7fffffff
	// hxf685469.Len = ?

	hxf03a9a7 := (*sliceHeader)(unsafe.Pointer(&x.Script))
	hxf03a9a7.Data = uintptr(unsafe.Pointer(x.ref1da77736.script))
	hxf03a9a7.Cap = 0x7fffffff
	// hxf03a9a7.Len = ?

	x.Shared = (uint16)(x.ref1da77736.shared)
	packSSByte(x.SpankJobEnv, x.ref1da77736.spank_job_env)
	x.SpankJobEnvSize = (uint32)(x.ref1da77736.spank_job_env_size)
	x.TaskDist = (uint32)(x.ref1da77736.task_dist)
	x.TimeLimit = (uint32)(x.ref1da77736.time_limit)
	x.TimeMin = (uint32)(x.ref1da77736.time_min)
	x.UserId = (uint32)(x.ref1da77736.user_id)
	x.WaitAllNodes = (uint16)(x.ref1da77736.wait_all_nodes)
	x.WarnFlags = (uint16)(x.ref1da77736.warn_flags)
	x.WarnSignal = (uint16)(x.ref1da77736.warn_signal)
	x.WarnTime = (uint16)(x.ref1da77736.warn_time)
	hxfe93325 := (*sliceHeader)(unsafe.Pointer(&x.WorkDir))
	hxfe93325.Data = uintptr(unsafe.Pointer(x.ref1da77736.work_dir))
	hxfe93325.Cap = 0x7fffffff
	// hxfe93325.Len = ?

	x.CpusPerTask = (uint16)(x.ref1da77736.cpus_per_task)
	x.MinCpus = (uint32)(x.ref1da77736.min_cpus)
	x.MaxCpus = (uint32)(x.ref1da77736.max_cpus)
	x.MinNodes = (uint32)(x.ref1da77736.min_nodes)
	x.MaxNodes = (uint32)(x.ref1da77736.max_nodes)
	x.BoardsPerNode = (uint16)(x.ref1da77736.boards_per_node)
	x.SocketsPerBoard = (uint16)(x.ref1da77736.sockets_per_board)
	x.SocketsPerNode = (uint16)(x.ref1da77736.sockets_per_node)
	x.CoresPerSocket = (uint16)(x.ref1da77736.cores_per_socket)
	x.ThreadsPerCore = (uint16)(x.ref1da77736.threads_per_core)
	x.NtasksPerNode = (uint16)(x.ref1da77736.ntasks_per_node)
	x.NtasksPerSocket = (uint16)(x.ref1da77736.ntasks_per_socket)
	x.NtasksPerCore = (uint16)(x.ref1da77736.ntasks_per_core)
	x.NtasksPerBoard = (uint16)(x.ref1da77736.ntasks_per_board)
	x.PnMinCpus = (uint16)(x.ref1da77736.pn_min_cpus)
	x.PnMinMemory = (uint)(x.ref1da77736.pn_min_memory)
	x.PnMinTmpDisk = (uint32)(x.ref1da77736.pn_min_tmp_disk)
	x.Geometry = *(*[5]uint16)(unsafe.Pointer(&x.ref1da77736.geometry))
	x.ConnType = *(*[5]uint16)(unsafe.Pointer(&x.ref1da77736.conn_type))
	x.Rotate = (uint16)(x.ref1da77736.rotate)
	hxf09ea94 := (*sliceHeader)(unsafe.Pointer(&x.Blrtsimage))
	hxf09ea94.Data = uintptr(unsafe.Pointer(x.ref1da77736.blrtsimage))
	hxf09ea94.Cap = 0x7fffffff
	// hxf09ea94.Len = ?

	hxfd687ee := (*sliceHeader)(unsafe.Pointer(&x.Linuximage))
	hxfd687ee.Data = uintptr(unsafe.Pointer(x.ref1da77736.linuximage))
	hxfd687ee.Cap = 0x7fffffff
	// hxfd687ee.Len = ?

	hxf15a567 := (*sliceHeader)(unsafe.Pointer(&x.Mloaderimage))
	hxf15a567.Data = uintptr(unsafe.Pointer(x.ref1da77736.mloaderimage))
	hxf15a567.Cap = 0x7fffffff
	// hxf15a567.Len = ?

	hxf8aebb5 := (*sliceHeader)(unsafe.Pointer(&x.Ramdiskimage))
	hxf8aebb5.Data = uintptr(unsafe.Pointer(x.ref1da77736.ramdiskimage))
	hxf8aebb5.Cap = 0x7fffffff
	// hxf8aebb5.Len = ?

	x.ReqSwitch = (uint32)(x.ref1da77736.req_switch)
	hxf5d30cf := (*sliceHeader)(unsafe.Pointer(&x.StdErr))
	hxf5d30cf.Data = uintptr(unsafe.Pointer(x.ref1da77736.std_err))
	hxf5d30cf.Cap = 0x7fffffff
	// hxf5d30cf.Len = ?

	hxf882e98 := (*sliceHeader)(unsafe.Pointer(&x.StdIn))
	hxf882e98.Data = uintptr(unsafe.Pointer(x.ref1da77736.std_in))
	hxf882e98.Cap = 0x7fffffff
	// hxf882e98.Len = ?

	hxf992404 := (*sliceHeader)(unsafe.Pointer(&x.StdOut))
	hxf992404.Data = uintptr(unsafe.Pointer(x.ref1da77736.std_out))
	hxf992404.Cap = 0x7fffffff
	// hxf992404.Len = ?

	hxf8e0dd2 := (*sliceHeader)(unsafe.Pointer(&x.TresReqCnt))
	hxf8e0dd2.Data = uintptr(unsafe.Pointer(x.ref1da77736.tres_req_cnt))
	hxf8e0dd2.Cap = 0x7fffffff
	// hxf8e0dd2.Len = ?

	x.Wait4switch = (uint32)(x.ref1da77736.wait4switch)
	hxf44d909 := (*sliceHeader)(unsafe.Pointer(&x.Wckey))
	hxf44d909.Data = uintptr(unsafe.Pointer(x.ref1da77736.wckey))
	hxf44d909.Cap = 0x7fffffff
	// hxf44d909.Len = ?

	x.X11 = (uint16)(x.ref1da77736.x11)
	hxfa835e7 := (*sliceHeader)(unsafe.Pointer(&x.X11MagicCookie))
	hxfa835e7.Data = uintptr(unsafe.Pointer(x.ref1da77736.x11_magic_cookie))
	hxfa835e7.Cap = 0x7fffffff
	// hxfa835e7.Len = ?

	x.X11TargetPort = (uint16)(x.ref1da77736.x11_target_port)
}

// allocJobInfoMemory allocates memory for type C.slurm_job_info_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocJobInfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfJobInfoValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfJobInfoValue = unsafe.Sizeof([1]C.slurm_job_info_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *JobInfo) Ref() *C.slurm_job_info_t {
	if x == nil {
		return nil
	}
	return x.refc83953cc
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *JobInfo) Free() {
	if x != nil && x.allocsc83953cc != nil {
		x.allocsc83953cc.(*cgoAllocMap).Free()
		x.refc83953cc = nil
	}
}

// NewJobInfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewJobInfoRef(ref unsafe.Pointer) *JobInfo {
	if ref == nil {
		return nil
	}
	obj := new(JobInfo)
	obj.refc83953cc = (*C.slurm_job_info_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *JobInfo) PassRef() (*C.slurm_job_info_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refc83953cc != nil {
		return x.refc83953cc, nil
	}
	memc83953cc := allocJobInfoMemory(1)
	refc83953cc := (*C.slurm_job_info_t)(memc83953cc)
	allocsc83953cc := new(cgoAllocMap)
	allocsc83953cc.Add(memc83953cc)

	var caccount_allocs *cgoAllocMap
	refc83953cc.account, caccount_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Account)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(caccount_allocs)

	var cadmin_comment_allocs *cgoAllocMap
	refc83953cc.admin_comment, cadmin_comment_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.AdminComment)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cadmin_comment_allocs)

	var calloc_node_allocs *cgoAllocMap
	refc83953cc.alloc_node, calloc_node_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.AllocNode)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(calloc_node_allocs)

	var calloc_sid_allocs *cgoAllocMap
	refc83953cc.alloc_sid, calloc_sid_allocs = (C.uint32_t)(x.AllocSid), cgoAllocsUnknown
	allocsc83953cc.Borrow(calloc_sid_allocs)

	var carray_bitmap_allocs *cgoAllocMap
	refc83953cc.array_bitmap, carray_bitmap_allocs = *(*unsafe.Pointer)(unsafe.Pointer(&x.ArrayBitmap)), cgoAllocsUnknown
	allocsc83953cc.Borrow(carray_bitmap_allocs)

	var carray_job_id_allocs *cgoAllocMap
	refc83953cc.array_job_id, carray_job_id_allocs = (C.uint32_t)(x.ArrayJobId), cgoAllocsUnknown
	allocsc83953cc.Borrow(carray_job_id_allocs)

	var carray_task_id_allocs *cgoAllocMap
	refc83953cc.array_task_id, carray_task_id_allocs = (C.uint32_t)(x.ArrayTaskId), cgoAllocsUnknown
	allocsc83953cc.Borrow(carray_task_id_allocs)

	var carray_max_tasks_allocs *cgoAllocMap
	refc83953cc.array_max_tasks, carray_max_tasks_allocs = (C.uint32_t)(x.ArrayMaxTasks), cgoAllocsUnknown
	allocsc83953cc.Borrow(carray_max_tasks_allocs)

	var carray_task_str_allocs *cgoAllocMap
	refc83953cc.array_task_str, carray_task_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ArrayTaskStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(carray_task_str_allocs)

	var cassoc_id_allocs *cgoAllocMap
	refc83953cc.assoc_id, cassoc_id_allocs = (C.uint32_t)(x.AssocId), cgoAllocsUnknown
	allocsc83953cc.Borrow(cassoc_id_allocs)

	var cbatch_flag_allocs *cgoAllocMap
	refc83953cc.batch_flag, cbatch_flag_allocs = (C.uint16_t)(x.BatchFlag), cgoAllocsUnknown
	allocsc83953cc.Borrow(cbatch_flag_allocs)

	var cbatch_host_allocs *cgoAllocMap
	refc83953cc.batch_host, cbatch_host_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.BatchHost)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cbatch_host_allocs)

	var cbitflags_allocs *cgoAllocMap
	refc83953cc.bitflags, cbitflags_allocs = (C.uint32_t)(x.Bitflags), cgoAllocsUnknown
	allocsc83953cc.Borrow(cbitflags_allocs)

	var cboards_per_node_allocs *cgoAllocMap
	refc83953cc.boards_per_node, cboards_per_node_allocs = (C.uint16_t)(x.BoardsPerNode), cgoAllocsUnknown
	allocsc83953cc.Borrow(cboards_per_node_allocs)

	var cburst_buffer_allocs *cgoAllocMap
	refc83953cc.burst_buffer, cburst_buffer_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.BurstBuffer)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cburst_buffer_allocs)

	var cburst_buffer_state_allocs *cgoAllocMap
	refc83953cc.burst_buffer_state, cburst_buffer_state_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.BurstBufferState)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cburst_buffer_state_allocs)

	var ccluster_allocs *cgoAllocMap
	refc83953cc.cluster, ccluster_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Cluster)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccluster_allocs)

	var ccluster_features_allocs *cgoAllocMap
	refc83953cc.cluster_features, ccluster_features_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ClusterFeatures)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccluster_features_allocs)

	var ccommand_allocs *cgoAllocMap
	refc83953cc.command, ccommand_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Command)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccommand_allocs)

	var ccomment_allocs *cgoAllocMap
	refc83953cc.comment, ccomment_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Comment)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccomment_allocs)

	var ccontiguous_allocs *cgoAllocMap
	refc83953cc.contiguous, ccontiguous_allocs = (C.uint16_t)(x.Contiguous), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccontiguous_allocs)

	var ccore_spec_allocs *cgoAllocMap
	refc83953cc.core_spec, ccore_spec_allocs = (C.uint16_t)(x.CoreSpec), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccore_spec_allocs)

	var ccores_per_socket_allocs *cgoAllocMap
	refc83953cc.cores_per_socket, ccores_per_socket_allocs = (C.uint16_t)(x.CoresPerSocket), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccores_per_socket_allocs)

	var cbillable_tres_allocs *cgoAllocMap
	refc83953cc.billable_tres, cbillable_tres_allocs = (C.double)(x.BillableTres), cgoAllocsUnknown
	allocsc83953cc.Borrow(cbillable_tres_allocs)

	var ccpus_per_task_allocs *cgoAllocMap
	refc83953cc.cpus_per_task, ccpus_per_task_allocs = (C.uint16_t)(x.CpusPerTask), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccpus_per_task_allocs)

	var ccpu_freq_min_allocs *cgoAllocMap
	refc83953cc.cpu_freq_min, ccpu_freq_min_allocs = (C.uint32_t)(x.CpuFreqMin), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccpu_freq_min_allocs)

	var ccpu_freq_max_allocs *cgoAllocMap
	refc83953cc.cpu_freq_max, ccpu_freq_max_allocs = (C.uint32_t)(x.CpuFreqMax), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccpu_freq_max_allocs)

	var ccpu_freq_gov_allocs *cgoAllocMap
	refc83953cc.cpu_freq_gov, ccpu_freq_gov_allocs = (C.uint32_t)(x.CpuFreqGov), cgoAllocsUnknown
	allocsc83953cc.Borrow(ccpu_freq_gov_allocs)

	var cdeadline_allocs *cgoAllocMap
	refc83953cc.deadline, cdeadline_allocs = (C.time_t)(x.Deadline), cgoAllocsUnknown
	allocsc83953cc.Borrow(cdeadline_allocs)

	var cdelay_boot_allocs *cgoAllocMap
	refc83953cc.delay_boot, cdelay_boot_allocs = (C.uint32_t)(x.DelayBoot), cgoAllocsUnknown
	allocsc83953cc.Borrow(cdelay_boot_allocs)

	var cdependency_allocs *cgoAllocMap
	refc83953cc.dependency, cdependency_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Dependency)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cdependency_allocs)

	var cderived_ec_allocs *cgoAllocMap
	refc83953cc.derived_ec, cderived_ec_allocs = (C.uint32_t)(x.DerivedEc), cgoAllocsUnknown
	allocsc83953cc.Borrow(cderived_ec_allocs)

	var celigible_time_allocs *cgoAllocMap
	refc83953cc.eligible_time, celigible_time_allocs = (C.time_t)(x.EligibleTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(celigible_time_allocs)

	var cend_time_allocs *cgoAllocMap
	refc83953cc.end_time, cend_time_allocs = (C.time_t)(x.EndTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(cend_time_allocs)

	var cexc_nodes_allocs *cgoAllocMap
	refc83953cc.exc_nodes, cexc_nodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ExcNodes)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cexc_nodes_allocs)

	var cexc_node_inx_allocs *cgoAllocMap
	refc83953cc.exc_node_inx, cexc_node_inx_allocs = (*C.int32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ExcNodeInx)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cexc_node_inx_allocs)

	var cexit_code_allocs *cgoAllocMap
	refc83953cc.exit_code, cexit_code_allocs = (C.uint32_t)(x.ExitCode), cgoAllocsUnknown
	allocsc83953cc.Borrow(cexit_code_allocs)

	var cfeatures_allocs *cgoAllocMap
	refc83953cc.features, cfeatures_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Features)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfeatures_allocs)

	var cfed_origin_str_allocs *cgoAllocMap
	refc83953cc.fed_origin_str, cfed_origin_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.FedOriginStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfed_origin_str_allocs)

	var cfed_siblings_active_allocs *cgoAllocMap
	refc83953cc.fed_siblings_active, cfed_siblings_active_allocs = (C.uint64_t)(x.FedSiblingsActive), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfed_siblings_active_allocs)

	var cfed_siblings_active_str_allocs *cgoAllocMap
	refc83953cc.fed_siblings_active_str, cfed_siblings_active_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.FedSiblingsActiveStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfed_siblings_active_str_allocs)

	var cfed_siblings_viable_allocs *cgoAllocMap
	refc83953cc.fed_siblings_viable, cfed_siblings_viable_allocs = (C.uint64_t)(x.FedSiblingsViable), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfed_siblings_viable_allocs)

	var cfed_siblings_viable_str_allocs *cgoAllocMap
	refc83953cc.fed_siblings_viable_str, cfed_siblings_viable_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.FedSiblingsViableStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cfed_siblings_viable_str_allocs)

	var cgres_allocs *cgoAllocMap
	refc83953cc.gres, cgres_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Gres)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cgres_allocs)

	var cgres_detail_cnt_allocs *cgoAllocMap
	refc83953cc.gres_detail_cnt, cgres_detail_cnt_allocs = (C.uint32_t)(x.GresDetailCnt), cgoAllocsUnknown
	allocsc83953cc.Borrow(cgres_detail_cnt_allocs)

	var cgres_detail_str_allocs *cgoAllocMap
	refc83953cc.gres_detail_str, cgres_detail_str_allocs = unpackSSByte(x.GresDetailStr)
	allocsc83953cc.Borrow(cgres_detail_str_allocs)

	var cgroup_id_allocs *cgoAllocMap
	refc83953cc.group_id, cgroup_id_allocs = (C.uint32_t)(x.GroupId), cgoAllocsUnknown
	allocsc83953cc.Borrow(cgroup_id_allocs)

	var cjob_id_allocs *cgoAllocMap
	refc83953cc.job_id, cjob_id_allocs = (C.uint32_t)(x.JobId), cgoAllocsUnknown
	allocsc83953cc.Borrow(cjob_id_allocs)

	var cjob_state_allocs *cgoAllocMap
	refc83953cc.job_state, cjob_state_allocs = (C.uint32_t)(x.JobState), cgoAllocsUnknown
	allocsc83953cc.Borrow(cjob_state_allocs)

	var clast_sched_eval_allocs *cgoAllocMap
	refc83953cc.last_sched_eval, clast_sched_eval_allocs = (C.time_t)(x.LastSchedEval), cgoAllocsUnknown
	allocsc83953cc.Borrow(clast_sched_eval_allocs)

	var clicenses_allocs *cgoAllocMap
	refc83953cc.licenses, clicenses_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Licenses)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(clicenses_allocs)

	var cmax_cpus_allocs *cgoAllocMap
	refc83953cc.max_cpus, cmax_cpus_allocs = (C.uint32_t)(x.MaxCpus), cgoAllocsUnknown
	allocsc83953cc.Borrow(cmax_cpus_allocs)

	var cmax_nodes_allocs *cgoAllocMap
	refc83953cc.max_nodes, cmax_nodes_allocs = (C.uint32_t)(x.MaxNodes), cgoAllocsUnknown
	allocsc83953cc.Borrow(cmax_nodes_allocs)

	var cmcs_label_allocs *cgoAllocMap
	refc83953cc.mcs_label, cmcs_label_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.McsLabel)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cmcs_label_allocs)

	var cname_allocs *cgoAllocMap
	refc83953cc.name, cname_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Name)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cname_allocs)

	var cnetwork_allocs *cgoAllocMap
	refc83953cc.network, cnetwork_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Network)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnetwork_allocs)

	var cnodes_allocs *cgoAllocMap
	refc83953cc.nodes, cnodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Nodes)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnodes_allocs)

	var cnice_allocs *cgoAllocMap
	refc83953cc.nice, cnice_allocs = (C.uint32_t)(x.Nice), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnice_allocs)

	var cnode_inx_allocs *cgoAllocMap
	refc83953cc.node_inx, cnode_inx_allocs = (*C.int32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.NodeInx)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnode_inx_allocs)

	var cntasks_per_core_allocs *cgoAllocMap
	refc83953cc.ntasks_per_core, cntasks_per_core_allocs = (C.uint16_t)(x.NtasksPerCore), cgoAllocsUnknown
	allocsc83953cc.Borrow(cntasks_per_core_allocs)

	var cntasks_per_node_allocs *cgoAllocMap
	refc83953cc.ntasks_per_node, cntasks_per_node_allocs = (C.uint16_t)(x.NtasksPerNode), cgoAllocsUnknown
	allocsc83953cc.Borrow(cntasks_per_node_allocs)

	var cntasks_per_socket_allocs *cgoAllocMap
	refc83953cc.ntasks_per_socket, cntasks_per_socket_allocs = (C.uint16_t)(x.NtasksPerSocket), cgoAllocsUnknown
	allocsc83953cc.Borrow(cntasks_per_socket_allocs)

	var cntasks_per_board_allocs *cgoAllocMap
	refc83953cc.ntasks_per_board, cntasks_per_board_allocs = (C.uint16_t)(x.NtasksPerBoard), cgoAllocsUnknown
	allocsc83953cc.Borrow(cntasks_per_board_allocs)

	var cnum_cpus_allocs *cgoAllocMap
	refc83953cc.num_cpus, cnum_cpus_allocs = (C.uint32_t)(x.NumCpus), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnum_cpus_allocs)

	var cnum_nodes_allocs *cgoAllocMap
	refc83953cc.num_nodes, cnum_nodes_allocs = (C.uint32_t)(x.NumNodes), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnum_nodes_allocs)

	var cnum_tasks_allocs *cgoAllocMap
	refc83953cc.num_tasks, cnum_tasks_allocs = (C.uint32_t)(x.NumTasks), cgoAllocsUnknown
	allocsc83953cc.Borrow(cnum_tasks_allocs)

	var cpack_job_id_allocs *cgoAllocMap
	refc83953cc.pack_job_id, cpack_job_id_allocs = (C.uint32_t)(x.PackJobId), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpack_job_id_allocs)

	var cpack_job_id_set_allocs *cgoAllocMap
	refc83953cc.pack_job_id_set, cpack_job_id_set_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.PackJobIdSet)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpack_job_id_set_allocs)

	var cpack_job_offset_allocs *cgoAllocMap
	refc83953cc.pack_job_offset, cpack_job_offset_allocs = (C.uint32_t)(x.PackJobOffset), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpack_job_offset_allocs)

	var cpartition_allocs *cgoAllocMap
	refc83953cc.partition, cpartition_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Partition)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpartition_allocs)

	var cpn_min_memory_allocs *cgoAllocMap
	refc83953cc.pn_min_memory, cpn_min_memory_allocs = (C.uint64_t)(x.PnMinMemory), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpn_min_memory_allocs)

	var cpn_min_cpus_allocs *cgoAllocMap
	refc83953cc.pn_min_cpus, cpn_min_cpus_allocs = (C.uint16_t)(x.PnMinCpus), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpn_min_cpus_allocs)

	var cpn_min_tmp_disk_allocs *cgoAllocMap
	refc83953cc.pn_min_tmp_disk, cpn_min_tmp_disk_allocs = (C.uint32_t)(x.PnMinTmpDisk), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpn_min_tmp_disk_allocs)

	var cpower_flags_allocs *cgoAllocMap
	refc83953cc.power_flags, cpower_flags_allocs = (C.uint8_t)(x.PowerFlags), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpower_flags_allocs)

	var cpreempt_time_allocs *cgoAllocMap
	refc83953cc.preempt_time, cpreempt_time_allocs = (C.time_t)(x.PreemptTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpreempt_time_allocs)

	var cpre_sus_time_allocs *cgoAllocMap
	refc83953cc.pre_sus_time, cpre_sus_time_allocs = (C.time_t)(x.PreSusTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpre_sus_time_allocs)

	var cpriority_allocs *cgoAllocMap
	refc83953cc.priority, cpriority_allocs = (C.uint32_t)(x.Priority), cgoAllocsUnknown
	allocsc83953cc.Borrow(cpriority_allocs)

	var cprofile_allocs *cgoAllocMap
	refc83953cc.profile, cprofile_allocs = (C.uint32_t)(x.Profile), cgoAllocsUnknown
	allocsc83953cc.Borrow(cprofile_allocs)

	var cqos_allocs *cgoAllocMap
	refc83953cc.qos, cqos_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Qos)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cqos_allocs)

	var creboot_allocs *cgoAllocMap
	refc83953cc.reboot, creboot_allocs = (C.uint8_t)(x.Reboot), cgoAllocsUnknown
	allocsc83953cc.Borrow(creboot_allocs)

	var creq_nodes_allocs *cgoAllocMap
	refc83953cc.req_nodes, creq_nodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ReqNodes)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(creq_nodes_allocs)

	var creq_node_inx_allocs *cgoAllocMap
	refc83953cc.req_node_inx, creq_node_inx_allocs = (*C.int32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ReqNodeInx)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(creq_node_inx_allocs)

	var creq_switch_allocs *cgoAllocMap
	refc83953cc.req_switch, creq_switch_allocs = (C.uint32_t)(x.ReqSwitch), cgoAllocsUnknown
	allocsc83953cc.Borrow(creq_switch_allocs)

	var crequeue_allocs *cgoAllocMap
	refc83953cc.requeue, crequeue_allocs = (C.uint16_t)(x.Requeue), cgoAllocsUnknown
	allocsc83953cc.Borrow(crequeue_allocs)

	var cresize_time_allocs *cgoAllocMap
	refc83953cc.resize_time, cresize_time_allocs = (C.time_t)(x.ResizeTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(cresize_time_allocs)

	var crestart_cnt_allocs *cgoAllocMap
	refc83953cc.restart_cnt, crestart_cnt_allocs = (C.uint16_t)(x.RestartCnt), cgoAllocsUnknown
	allocsc83953cc.Borrow(crestart_cnt_allocs)

	var cresv_name_allocs *cgoAllocMap
	refc83953cc.resv_name, cresv_name_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ResvName)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cresv_name_allocs)

	var csched_nodes_allocs *cgoAllocMap
	refc83953cc.sched_nodes, csched_nodes_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.SchedNodes)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(csched_nodes_allocs)

	var cshared_allocs *cgoAllocMap
	refc83953cc.shared, cshared_allocs = (C.uint16_t)(x.Shared), cgoAllocsUnknown
	allocsc83953cc.Borrow(cshared_allocs)

	var cshow_flags_allocs *cgoAllocMap
	refc83953cc.show_flags, cshow_flags_allocs = (C.uint16_t)(x.ShowFlags), cgoAllocsUnknown
	allocsc83953cc.Borrow(cshow_flags_allocs)

	var csockets_per_board_allocs *cgoAllocMap
	refc83953cc.sockets_per_board, csockets_per_board_allocs = (C.uint16_t)(x.SocketsPerBoard), cgoAllocsUnknown
	allocsc83953cc.Borrow(csockets_per_board_allocs)

	var csockets_per_node_allocs *cgoAllocMap
	refc83953cc.sockets_per_node, csockets_per_node_allocs = (C.uint16_t)(x.SocketsPerNode), cgoAllocsUnknown
	allocsc83953cc.Borrow(csockets_per_node_allocs)

	var cstart_time_allocs *cgoAllocMap
	refc83953cc.start_time, cstart_time_allocs = (C.time_t)(x.StartTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstart_time_allocs)

	var cstart_protocol_ver_allocs *cgoAllocMap
	refc83953cc.start_protocol_ver, cstart_protocol_ver_allocs = (C.uint16_t)(x.StartProtocolVer), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstart_protocol_ver_allocs)

	var cstate_desc_allocs *cgoAllocMap
	refc83953cc.state_desc, cstate_desc_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StateDesc)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstate_desc_allocs)

	var cstate_reason_allocs *cgoAllocMap
	refc83953cc.state_reason, cstate_reason_allocs = (C.uint16_t)(x.StateReason), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstate_reason_allocs)

	var cstd_err_allocs *cgoAllocMap
	refc83953cc.std_err, cstd_err_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdErr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstd_err_allocs)

	var cstd_in_allocs *cgoAllocMap
	refc83953cc.std_in, cstd_in_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdIn)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstd_in_allocs)

	var cstd_out_allocs *cgoAllocMap
	refc83953cc.std_out, cstd_out_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.StdOut)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cstd_out_allocs)

	var csubmit_time_allocs *cgoAllocMap
	refc83953cc.submit_time, csubmit_time_allocs = (C.time_t)(x.SubmitTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(csubmit_time_allocs)

	var csuspend_time_allocs *cgoAllocMap
	refc83953cc.suspend_time, csuspend_time_allocs = (C.time_t)(x.SuspendTime), cgoAllocsUnknown
	allocsc83953cc.Borrow(csuspend_time_allocs)

	var ctime_limit_allocs *cgoAllocMap
	refc83953cc.time_limit, ctime_limit_allocs = (C.uint32_t)(x.TimeLimit), cgoAllocsUnknown
	allocsc83953cc.Borrow(ctime_limit_allocs)

	var ctime_min_allocs *cgoAllocMap
	refc83953cc.time_min, ctime_min_allocs = (C.uint32_t)(x.TimeMin), cgoAllocsUnknown
	allocsc83953cc.Borrow(ctime_min_allocs)

	var cthreads_per_core_allocs *cgoAllocMap
	refc83953cc.threads_per_core, cthreads_per_core_allocs = (C.uint16_t)(x.ThreadsPerCore), cgoAllocsUnknown
	allocsc83953cc.Borrow(cthreads_per_core_allocs)

	var ctres_req_str_allocs *cgoAllocMap
	refc83953cc.tres_req_str, ctres_req_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.TresReqStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ctres_req_str_allocs)

	var ctres_alloc_str_allocs *cgoAllocMap
	refc83953cc.tres_alloc_str, ctres_alloc_str_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.TresAllocStr)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(ctres_alloc_str_allocs)

	var cuser_id_allocs *cgoAllocMap
	refc83953cc.user_id, cuser_id_allocs = (C.uint32_t)(x.UserId), cgoAllocsUnknown
	allocsc83953cc.Borrow(cuser_id_allocs)

	var cuser_name_allocs *cgoAllocMap
	refc83953cc.user_name, cuser_name_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.UserName)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cuser_name_allocs)

	var cwait4switch_allocs *cgoAllocMap
	refc83953cc.wait4switch, cwait4switch_allocs = (C.uint32_t)(x.Wait4switch), cgoAllocsUnknown
	allocsc83953cc.Borrow(cwait4switch_allocs)

	var cwckey_allocs *cgoAllocMap
	refc83953cc.wckey, cwckey_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Wckey)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cwckey_allocs)

	var cwork_dir_allocs *cgoAllocMap
	refc83953cc.work_dir, cwork_dir_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.WorkDir)).Data)), cgoAllocsUnknown
	allocsc83953cc.Borrow(cwork_dir_allocs)

	x.refc83953cc = refc83953cc
	x.allocsc83953cc = allocsc83953cc
	return refc83953cc, allocsc83953cc

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x JobInfo) PassValue() (C.slurm_job_info_t, *cgoAllocMap) {
	if x.refc83953cc != nil {
		return *x.refc83953cc, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *JobInfo) Deref() {
	if x.refc83953cc == nil {
		return
	}
	hxf8eae10 := (*sliceHeader)(unsafe.Pointer(&x.Account))
	hxf8eae10.Data = uintptr(unsafe.Pointer(x.refc83953cc.account))
	hxf8eae10.Cap = 0x7fffffff
	// hxf8eae10.Len = ?

	hxfeb55cf := (*sliceHeader)(unsafe.Pointer(&x.AdminComment))
	hxfeb55cf.Data = uintptr(unsafe.Pointer(x.refc83953cc.admin_comment))
	hxfeb55cf.Cap = 0x7fffffff
	// hxfeb55cf.Len = ?

	hxf458096 := (*sliceHeader)(unsafe.Pointer(&x.AllocNode))
	hxf458096.Data = uintptr(unsafe.Pointer(x.refc83953cc.alloc_node))
	hxf458096.Cap = 0x7fffffff
	// hxf458096.Len = ?

	x.AllocSid = (uint32)(x.refc83953cc.alloc_sid)
	x.ArrayBitmap = (unsafe.Pointer)(unsafe.Pointer(x.refc83953cc.array_bitmap))
	x.ArrayJobId = (uint32)(x.refc83953cc.array_job_id)
	x.ArrayTaskId = (uint32)(x.refc83953cc.array_task_id)
	x.ArrayMaxTasks = (uint32)(x.refc83953cc.array_max_tasks)
	hxf9aab83 := (*sliceHeader)(unsafe.Pointer(&x.ArrayTaskStr))
	hxf9aab83.Data = uintptr(unsafe.Pointer(x.refc83953cc.array_task_str))
	hxf9aab83.Cap = 0x7fffffff
	// hxf9aab83.Len = ?

	x.AssocId = (uint32)(x.refc83953cc.assoc_id)
	x.BatchFlag = (uint16)(x.refc83953cc.batch_flag)
	hxf8b35a8 := (*sliceHeader)(unsafe.Pointer(&x.BatchHost))
	hxf8b35a8.Data = uintptr(unsafe.Pointer(x.refc83953cc.batch_host))
	hxf8b35a8.Cap = 0x7fffffff
	// hxf8b35a8.Len = ?

	x.Bitflags = (uint32)(x.refc83953cc.bitflags)
	x.BoardsPerNode = (uint16)(x.refc83953cc.boards_per_node)
	hxf8959c2 := (*sliceHeader)(unsafe.Pointer(&x.BurstBuffer))
	hxf8959c2.Data = uintptr(unsafe.Pointer(x.refc83953cc.burst_buffer))
	hxf8959c2.Cap = 0x7fffffff
	// hxf8959c2.Len = ?

	hxfb029a7 := (*sliceHeader)(unsafe.Pointer(&x.BurstBufferState))
	hxfb029a7.Data = uintptr(unsafe.Pointer(x.refc83953cc.burst_buffer_state))
	hxfb029a7.Cap = 0x7fffffff
	// hxfb029a7.Len = ?

	hxf7d15a2 := (*sliceHeader)(unsafe.Pointer(&x.Cluster))
	hxf7d15a2.Data = uintptr(unsafe.Pointer(x.refc83953cc.cluster))
	hxf7d15a2.Cap = 0x7fffffff
	// hxf7d15a2.Len = ?

	hxf8dbbe5 := (*sliceHeader)(unsafe.Pointer(&x.ClusterFeatures))
	hxf8dbbe5.Data = uintptr(unsafe.Pointer(x.refc83953cc.cluster_features))
	hxf8dbbe5.Cap = 0x7fffffff
	// hxf8dbbe5.Len = ?

	hxf766ff8 := (*sliceHeader)(unsafe.Pointer(&x.Command))
	hxf766ff8.Data = uintptr(unsafe.Pointer(x.refc83953cc.command))
	hxf766ff8.Cap = 0x7fffffff
	// hxf766ff8.Len = ?

	hxf9b1633 := (*sliceHeader)(unsafe.Pointer(&x.Comment))
	hxf9b1633.Data = uintptr(unsafe.Pointer(x.refc83953cc.comment))
	hxf9b1633.Cap = 0x7fffffff
	// hxf9b1633.Len = ?

	x.Contiguous = (uint16)(x.refc83953cc.contiguous)
	x.CoreSpec = (uint16)(x.refc83953cc.core_spec)
	x.CoresPerSocket = (uint16)(x.refc83953cc.cores_per_socket)
	x.BillableTres = (float64)(x.refc83953cc.billable_tres)
	x.CpusPerTask = (uint16)(x.refc83953cc.cpus_per_task)
	x.CpuFreqMin = (uint32)(x.refc83953cc.cpu_freq_min)
	x.CpuFreqMax = (uint32)(x.refc83953cc.cpu_freq_max)
	x.CpuFreqGov = (uint32)(x.refc83953cc.cpu_freq_gov)
	x.Deadline = (int)(x.refc83953cc.deadline)
	x.DelayBoot = (uint32)(x.refc83953cc.delay_boot)
	hxf502c9a := (*sliceHeader)(unsafe.Pointer(&x.Dependency))
	hxf502c9a.Data = uintptr(unsafe.Pointer(x.refc83953cc.dependency))
	hxf502c9a.Cap = 0x7fffffff
	// hxf502c9a.Len = ?

	x.DerivedEc = (uint32)(x.refc83953cc.derived_ec)
	x.EligibleTime = (int)(x.refc83953cc.eligible_time)
	x.EndTime = (int)(x.refc83953cc.end_time)
	hxf4a9453 := (*sliceHeader)(unsafe.Pointer(&x.ExcNodes))
	hxf4a9453.Data = uintptr(unsafe.Pointer(x.refc83953cc.exc_nodes))
	hxf4a9453.Cap = 0x7fffffff
	// hxf4a9453.Len = ?

	hxf1a1416 := (*sliceHeader)(unsafe.Pointer(&x.ExcNodeInx))
	hxf1a1416.Data = uintptr(unsafe.Pointer(x.refc83953cc.exc_node_inx))
	hxf1a1416.Cap = 0x7fffffff
	// hxf1a1416.Len = ?

	x.ExitCode = (uint32)(x.refc83953cc.exit_code)
	hxf92be66 := (*sliceHeader)(unsafe.Pointer(&x.Features))
	hxf92be66.Data = uintptr(unsafe.Pointer(x.refc83953cc.features))
	hxf92be66.Cap = 0x7fffffff
	// hxf92be66.Len = ?

	hxf4b5187 := (*sliceHeader)(unsafe.Pointer(&x.FedOriginStr))
	hxf4b5187.Data = uintptr(unsafe.Pointer(x.refc83953cc.fed_origin_str))
	hxf4b5187.Cap = 0x7fffffff
	// hxf4b5187.Len = ?

	x.FedSiblingsActive = (uint)(x.refc83953cc.fed_siblings_active)
	hxf177f79 := (*sliceHeader)(unsafe.Pointer(&x.FedSiblingsActiveStr))
	hxf177f79.Data = uintptr(unsafe.Pointer(x.refc83953cc.fed_siblings_active_str))
	hxf177f79.Cap = 0x7fffffff
	// hxf177f79.Len = ?

	x.FedSiblingsViable = (uint)(x.refc83953cc.fed_siblings_viable)
	hxfaa359c := (*sliceHeader)(unsafe.Pointer(&x.FedSiblingsViableStr))
	hxfaa359c.Data = uintptr(unsafe.Pointer(x.refc83953cc.fed_siblings_viable_str))
	hxfaa359c.Cap = 0x7fffffff
	// hxfaa359c.Len = ?

	hxfa897de := (*sliceHeader)(unsafe.Pointer(&x.Gres))
	hxfa897de.Data = uintptr(unsafe.Pointer(x.refc83953cc.gres))
	hxfa897de.Cap = 0x7fffffff
	// hxfa897de.Len = ?

	x.GresDetailCnt = (uint32)(x.refc83953cc.gres_detail_cnt)
	packSSByte(x.GresDetailStr, x.refc83953cc.gres_detail_str)
	x.GroupId = (uint32)(x.refc83953cc.group_id)
	x.JobId = (uint32)(x.refc83953cc.job_id)
	x.JobState = (uint32)(x.refc83953cc.job_state)
	x.LastSchedEval = (int)(x.refc83953cc.last_sched_eval)
	hxf08bba9 := (*sliceHeader)(unsafe.Pointer(&x.Licenses))
	hxf08bba9.Data = uintptr(unsafe.Pointer(x.refc83953cc.licenses))
	hxf08bba9.Cap = 0x7fffffff
	// hxf08bba9.Len = ?

	x.MaxCpus = (uint32)(x.refc83953cc.max_cpus)
	x.MaxNodes = (uint32)(x.refc83953cc.max_nodes)
	hxfd3aa9c := (*sliceHeader)(unsafe.Pointer(&x.McsLabel))
	hxfd3aa9c.Data = uintptr(unsafe.Pointer(x.refc83953cc.mcs_label))
	hxfd3aa9c.Cap = 0x7fffffff
	// hxfd3aa9c.Len = ?

	hxfb2f596 := (*sliceHeader)(unsafe.Pointer(&x.Name))
	hxfb2f596.Data = uintptr(unsafe.Pointer(x.refc83953cc.name))
	hxfb2f596.Cap = 0x7fffffff
	// hxfb2f596.Len = ?

	hxf11683e := (*sliceHeader)(unsafe.Pointer(&x.Network))
	hxf11683e.Data = uintptr(unsafe.Pointer(x.refc83953cc.network))
	hxf11683e.Cap = 0x7fffffff
	// hxf11683e.Len = ?

	hxfd9261b := (*sliceHeader)(unsafe.Pointer(&x.Nodes))
	hxfd9261b.Data = uintptr(unsafe.Pointer(x.refc83953cc.nodes))
	hxfd9261b.Cap = 0x7fffffff
	// hxfd9261b.Len = ?

	x.Nice = (uint32)(x.refc83953cc.nice)
	hxf77d2ac := (*sliceHeader)(unsafe.Pointer(&x.NodeInx))
	hxf77d2ac.Data = uintptr(unsafe.Pointer(x.refc83953cc.node_inx))
	hxf77d2ac.Cap = 0x7fffffff
	// hxf77d2ac.Len = ?

	x.NtasksPerCore = (uint16)(x.refc83953cc.ntasks_per_core)
	x.NtasksPerNode = (uint16)(x.refc83953cc.ntasks_per_node)
	x.NtasksPerSocket = (uint16)(x.refc83953cc.ntasks_per_socket)
	x.NtasksPerBoard = (uint16)(x.refc83953cc.ntasks_per_board)
	x.NumCpus = (uint32)(x.refc83953cc.num_cpus)
	x.NumNodes = (uint32)(x.refc83953cc.num_nodes)
	x.NumTasks = (uint32)(x.refc83953cc.num_tasks)
	x.PackJobId = (uint32)(x.refc83953cc.pack_job_id)
	hxff6a91e := (*sliceHeader)(unsafe.Pointer(&x.PackJobIdSet))
	hxff6a91e.Data = uintptr(unsafe.Pointer(x.refc83953cc.pack_job_id_set))
	hxff6a91e.Cap = 0x7fffffff
	// hxff6a91e.Len = ?

	x.PackJobOffset = (uint32)(x.refc83953cc.pack_job_offset)
	hxf971c70 := (*sliceHeader)(unsafe.Pointer(&x.Partition))
	hxf971c70.Data = uintptr(unsafe.Pointer(x.refc83953cc.partition))
	hxf971c70.Cap = 0x7fffffff
	// hxf971c70.Len = ?

	x.PnMinMemory = (uint)(x.refc83953cc.pn_min_memory)
	x.PnMinCpus = (uint16)(x.refc83953cc.pn_min_cpus)
	x.PnMinTmpDisk = (uint32)(x.refc83953cc.pn_min_tmp_disk)
	x.PowerFlags = (byte)(x.refc83953cc.power_flags)
	x.PreemptTime = (int)(x.refc83953cc.preempt_time)
	x.PreSusTime = (int)(x.refc83953cc.pre_sus_time)
	x.Priority = (uint32)(x.refc83953cc.priority)
	x.Profile = (uint32)(x.refc83953cc.profile)
	hxf047235 := (*sliceHeader)(unsafe.Pointer(&x.Qos))
	hxf047235.Data = uintptr(unsafe.Pointer(x.refc83953cc.qos))
	hxf047235.Cap = 0x7fffffff
	// hxf047235.Len = ?

	x.Reboot = (byte)(x.refc83953cc.reboot)
	hxf612a5d := (*sliceHeader)(unsafe.Pointer(&x.ReqNodes))
	hxf612a5d.Data = uintptr(unsafe.Pointer(x.refc83953cc.req_nodes))
	hxf612a5d.Cap = 0x7fffffff
	// hxf612a5d.Len = ?

	hxff58be3 := (*sliceHeader)(unsafe.Pointer(&x.ReqNodeInx))
	hxff58be3.Data = uintptr(unsafe.Pointer(x.refc83953cc.req_node_inx))
	hxff58be3.Cap = 0x7fffffff
	// hxff58be3.Len = ?

	x.ReqSwitch = (uint32)(x.refc83953cc.req_switch)
	x.Requeue = (uint16)(x.refc83953cc.requeue)
	x.ResizeTime = (int)(x.refc83953cc.resize_time)
	x.RestartCnt = (uint16)(x.refc83953cc.restart_cnt)
	hxf79f3d5 := (*sliceHeader)(unsafe.Pointer(&x.ResvName))
	hxf79f3d5.Data = uintptr(unsafe.Pointer(x.refc83953cc.resv_name))
	hxf79f3d5.Cap = 0x7fffffff
	// hxf79f3d5.Len = ?

	hxfbb2d22 := (*sliceHeader)(unsafe.Pointer(&x.SchedNodes))
	hxfbb2d22.Data = uintptr(unsafe.Pointer(x.refc83953cc.sched_nodes))
	hxfbb2d22.Cap = 0x7fffffff
	// hxfbb2d22.Len = ?

	x.Shared = (uint16)(x.refc83953cc.shared)
	x.ShowFlags = (uint16)(x.refc83953cc.show_flags)
	x.SocketsPerBoard = (uint16)(x.refc83953cc.sockets_per_board)
	x.SocketsPerNode = (uint16)(x.refc83953cc.sockets_per_node)
	x.StartTime = (int)(x.refc83953cc.start_time)
	x.StartProtocolVer = (uint16)(x.refc83953cc.start_protocol_ver)
	hxff3831d := (*sliceHeader)(unsafe.Pointer(&x.StateDesc))
	hxff3831d.Data = uintptr(unsafe.Pointer(x.refc83953cc.state_desc))
	hxff3831d.Cap = 0x7fffffff
	// hxff3831d.Len = ?

	x.StateReason = (uint16)(x.refc83953cc.state_reason)
	hxf3b2498 := (*sliceHeader)(unsafe.Pointer(&x.StdErr))
	hxf3b2498.Data = uintptr(unsafe.Pointer(x.refc83953cc.std_err))
	hxf3b2498.Cap = 0x7fffffff
	// hxf3b2498.Len = ?

	hxfe80fc5 := (*sliceHeader)(unsafe.Pointer(&x.StdIn))
	hxfe80fc5.Data = uintptr(unsafe.Pointer(x.refc83953cc.std_in))
	hxfe80fc5.Cap = 0x7fffffff
	// hxfe80fc5.Len = ?

	hxfc03c44 := (*sliceHeader)(unsafe.Pointer(&x.StdOut))
	hxfc03c44.Data = uintptr(unsafe.Pointer(x.refc83953cc.std_out))
	hxfc03c44.Cap = 0x7fffffff
	// hxfc03c44.Len = ?

	x.SubmitTime = (int)(x.refc83953cc.submit_time)
	x.SuspendTime = (int)(x.refc83953cc.suspend_time)
	x.TimeLimit = (uint32)(x.refc83953cc.time_limit)
	x.TimeMin = (uint32)(x.refc83953cc.time_min)
	x.ThreadsPerCore = (uint16)(x.refc83953cc.threads_per_core)
	hxf32b611 := (*sliceHeader)(unsafe.Pointer(&x.TresReqStr))
	hxf32b611.Data = uintptr(unsafe.Pointer(x.refc83953cc.tres_req_str))
	hxf32b611.Cap = 0x7fffffff
	// hxf32b611.Len = ?

	hxf187e71 := (*sliceHeader)(unsafe.Pointer(&x.TresAllocStr))
	hxf187e71.Data = uintptr(unsafe.Pointer(x.refc83953cc.tres_alloc_str))
	hxf187e71.Cap = 0x7fffffff
	// hxf187e71.Len = ?

	x.UserId = (uint32)(x.refc83953cc.user_id)
	hxf13e50a := (*sliceHeader)(unsafe.Pointer(&x.UserName))
	hxf13e50a.Data = uintptr(unsafe.Pointer(x.refc83953cc.user_name))
	hxf13e50a.Cap = 0x7fffffff
	// hxf13e50a.Len = ?

	x.Wait4switch = (uint32)(x.refc83953cc.wait4switch)
	hxf9227c2 := (*sliceHeader)(unsafe.Pointer(&x.Wckey))
	hxf9227c2.Data = uintptr(unsafe.Pointer(x.refc83953cc.wckey))
	hxf9227c2.Cap = 0x7fffffff
	// hxf9227c2.Len = ?

	hxfa7b2ab := (*sliceHeader)(unsafe.Pointer(&x.WorkDir))
	hxfa7b2ab.Data = uintptr(unsafe.Pointer(x.refc83953cc.work_dir))
	hxfa7b2ab.Cap = 0x7fffffff
	// hxfa7b2ab.Len = ?

}

// allocJobInfoMsgMemory allocates memory for type C.job_info_msg_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocJobInfoMsgMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfJobInfoMsgValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfJobInfoMsgValue = unsafe.Sizeof([1]C.job_info_msg_t{})

// unpackSJobInfo transforms a sliced Go data structure into plain C format.
func unpackSJobInfo(x []JobInfo) (unpacked *C.slurm_job_info_t, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(&unpacked, func(**C.slurm_job_info_t) {
		go allocs.Free()
	})

	len0 := len(x)
	mem0 := allocJobInfoMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: uintptr(mem0),
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.slurm_job_info_t)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.slurm_job_info_t)(unsafe.Pointer(h.Data))
	return
}

// packSJobInfo reads sliced Go data structure out from plain C format.
func packSJobInfo(v []JobInfo, ptr0 *C.slurm_job_info_t) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfJobInfoValue]C.slurm_job_info_t)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewJobInfoRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *JobInfoMsg) Ref() *C.job_info_msg_t {
	if x == nil {
		return nil
	}
	return x.ref99f73760
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *JobInfoMsg) Free() {
	if x != nil && x.allocs99f73760 != nil {
		x.allocs99f73760.(*cgoAllocMap).Free()
		x.ref99f73760 = nil
	}
}

// NewJobInfoMsgRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewJobInfoMsgRef(ref unsafe.Pointer) *JobInfoMsg {
	if ref == nil {
		return nil
	}
	obj := new(JobInfoMsg)
	obj.ref99f73760 = (*C.job_info_msg_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *JobInfoMsg) PassRef() (*C.job_info_msg_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref99f73760 != nil {
		return x.ref99f73760, nil
	}
	mem99f73760 := allocJobInfoMsgMemory(1)
	ref99f73760 := (*C.job_info_msg_t)(mem99f73760)
	allocs99f73760 := new(cgoAllocMap)
	allocs99f73760.Add(mem99f73760)

	var clast_update_allocs *cgoAllocMap
	ref99f73760.last_update, clast_update_allocs = (C.time_t)(x.LastUpdate), cgoAllocsUnknown
	allocs99f73760.Borrow(clast_update_allocs)

	var crecord_count_allocs *cgoAllocMap
	ref99f73760.record_count, crecord_count_allocs = (C.uint32_t)(x.RecordCount), cgoAllocsUnknown
	allocs99f73760.Borrow(crecord_count_allocs)

	var cjob_array_allocs *cgoAllocMap
	ref99f73760.job_array, cjob_array_allocs = unpackSJobInfo(x.JobArray)
	allocs99f73760.Borrow(cjob_array_allocs)

	x.ref99f73760 = ref99f73760
	x.allocs99f73760 = allocs99f73760
	return ref99f73760, allocs99f73760

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x JobInfoMsg) PassValue() (C.job_info_msg_t, *cgoAllocMap) {
	if x.ref99f73760 != nil {
		return *x.ref99f73760, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *JobInfoMsg) Deref() {
	if x.ref99f73760 == nil {
		return
	}
	x.LastUpdate = (int)(x.ref99f73760.last_update)
	x.RecordCount = (uint32)(x.ref99f73760.record_count)
	packSJobInfo(x.JobArray, x.ref99f73760.job_array)
}

// allocSubmitResponseMsgMemory allocates memory for type C.submit_response_msg_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocSubmitResponseMsgMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfSubmitResponseMsgValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfSubmitResponseMsgValue = unsafe.Sizeof([1]C.submit_response_msg_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *SubmitResponseMsg) Ref() *C.submit_response_msg_t {
	if x == nil {
		return nil
	}
	return x.ref6c6e601
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *SubmitResponseMsg) Free() {
	if x != nil && x.allocs6c6e601 != nil {
		x.allocs6c6e601.(*cgoAllocMap).Free()
		x.ref6c6e601 = nil
	}
}

// NewSubmitResponseMsgRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewSubmitResponseMsgRef(ref unsafe.Pointer) *SubmitResponseMsg {
	if ref == nil {
		return nil
	}
	obj := new(SubmitResponseMsg)
	obj.ref6c6e601 = (*C.submit_response_msg_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *SubmitResponseMsg) PassRef() (*C.submit_response_msg_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref6c6e601 != nil {
		return x.ref6c6e601, nil
	}
	mem6c6e601 := allocSubmitResponseMsgMemory(1)
	ref6c6e601 := (*C.submit_response_msg_t)(mem6c6e601)
	allocs6c6e601 := new(cgoAllocMap)
	allocs6c6e601.Add(mem6c6e601)

	var cjob_id_allocs *cgoAllocMap
	ref6c6e601.job_id, cjob_id_allocs = (C.uint32_t)(x.JobId), cgoAllocsUnknown
	allocs6c6e601.Borrow(cjob_id_allocs)

	var cstep_id_allocs *cgoAllocMap
	ref6c6e601.step_id, cstep_id_allocs = (C.uint32_t)(x.StepId), cgoAllocsUnknown
	allocs6c6e601.Borrow(cstep_id_allocs)

	var cerror_code_allocs *cgoAllocMap
	ref6c6e601.error_code, cerror_code_allocs = (C.uint32_t)(x.ErrorCode), cgoAllocsUnknown
	allocs6c6e601.Borrow(cerror_code_allocs)

	var cjob_submit_user_msg_allocs *cgoAllocMap
	ref6c6e601.job_submit_user_msg, cjob_submit_user_msg_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.JobSubmitUserMsg)).Data)), cgoAllocsUnknown
	allocs6c6e601.Borrow(cjob_submit_user_msg_allocs)

	x.ref6c6e601 = ref6c6e601
	x.allocs6c6e601 = allocs6c6e601
	return ref6c6e601, allocs6c6e601

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x SubmitResponseMsg) PassValue() (C.submit_response_msg_t, *cgoAllocMap) {
	if x.ref6c6e601 != nil {
		return *x.ref6c6e601, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *SubmitResponseMsg) Deref() {
	if x.ref6c6e601 == nil {
		return
	}
	x.JobId = (uint32)(x.ref6c6e601.job_id)
	x.StepId = (uint32)(x.ref6c6e601.step_id)
	x.ErrorCode = (uint32)(x.ref6c6e601.error_code)
	hxfa34053 := (*sliceHeader)(unsafe.Pointer(&x.JobSubmitUserMsg))
	hxfa34053.Data = uintptr(unsafe.Pointer(x.ref6c6e601.job_submit_user_msg))
	hxfa34053.Cap = 0x7fffffff
	// hxfa34053.Len = ?

}

// allocTriggerInfoMemory allocates memory for type C.trigger_info_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocTriggerInfoMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfTriggerInfoValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfTriggerInfoValue = unsafe.Sizeof([1]C.trigger_info_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *TriggerInfo) Ref() *C.trigger_info_t {
	if x == nil {
		return nil
	}
	return x.ref1497cae7
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *TriggerInfo) Free() {
	if x != nil && x.allocs1497cae7 != nil {
		x.allocs1497cae7.(*cgoAllocMap).Free()
		x.ref1497cae7 = nil
	}
}

// NewTriggerInfoRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewTriggerInfoRef(ref unsafe.Pointer) *TriggerInfo {
	if ref == nil {
		return nil
	}
	obj := new(TriggerInfo)
	obj.ref1497cae7 = (*C.trigger_info_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *TriggerInfo) PassRef() (*C.trigger_info_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref1497cae7 != nil {
		return x.ref1497cae7, nil
	}
	mem1497cae7 := allocTriggerInfoMemory(1)
	ref1497cae7 := (*C.trigger_info_t)(mem1497cae7)
	allocs1497cae7 := new(cgoAllocMap)
	allocs1497cae7.Add(mem1497cae7)

	var cflags_allocs *cgoAllocMap
	ref1497cae7.flags, cflags_allocs = (C.uint16_t)(x.Flags), cgoAllocsUnknown
	allocs1497cae7.Borrow(cflags_allocs)

	var ctrig_id_allocs *cgoAllocMap
	ref1497cae7.trig_id, ctrig_id_allocs = (C.uint32_t)(x.TrigId), cgoAllocsUnknown
	allocs1497cae7.Borrow(ctrig_id_allocs)

	var cres_type_allocs *cgoAllocMap
	ref1497cae7.res_type, cres_type_allocs = (C.uint16_t)(x.ResType), cgoAllocsUnknown
	allocs1497cae7.Borrow(cres_type_allocs)

	var cres_id_allocs *cgoAllocMap
	ref1497cae7.res_id, cres_id_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.ResId)).Data)), cgoAllocsUnknown
	allocs1497cae7.Borrow(cres_id_allocs)

	var ctrig_type_allocs *cgoAllocMap
	ref1497cae7.trig_type, ctrig_type_allocs = (C.uint32_t)(x.TrigType), cgoAllocsUnknown
	allocs1497cae7.Borrow(ctrig_type_allocs)

	var coffset_allocs *cgoAllocMap
	ref1497cae7.offset, coffset_allocs = (C.uint16_t)(x.Offset), cgoAllocsUnknown
	allocs1497cae7.Borrow(coffset_allocs)

	var cuser_id_allocs *cgoAllocMap
	ref1497cae7.user_id, cuser_id_allocs = (C.uint32_t)(x.UserId), cgoAllocsUnknown
	allocs1497cae7.Borrow(cuser_id_allocs)

	var cprogram_allocs *cgoAllocMap
	ref1497cae7.program, cprogram_allocs = (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&x.Program)).Data)), cgoAllocsUnknown
	allocs1497cae7.Borrow(cprogram_allocs)

	x.ref1497cae7 = ref1497cae7
	x.allocs1497cae7 = allocs1497cae7
	return ref1497cae7, allocs1497cae7

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x TriggerInfo) PassValue() (C.trigger_info_t, *cgoAllocMap) {
	if x.ref1497cae7 != nil {
		return *x.ref1497cae7, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *TriggerInfo) Deref() {
	if x.ref1497cae7 == nil {
		return
	}
	x.Flags = (uint16)(x.ref1497cae7.flags)
	x.TrigId = (uint32)(x.ref1497cae7.trig_id)
	x.ResType = (uint16)(x.ref1497cae7.res_type)
	hxfe3c193 := (*sliceHeader)(unsafe.Pointer(&x.ResId))
	hxfe3c193.Data = uintptr(unsafe.Pointer(x.ref1497cae7.res_id))
	hxfe3c193.Cap = 0x7fffffff
	// hxfe3c193.Len = ?

	x.TrigType = (uint32)(x.ref1497cae7.trig_type)
	x.Offset = (uint16)(x.ref1497cae7.offset)
	x.UserId = (uint32)(x.ref1497cae7.user_id)
	hxfe8267c := (*sliceHeader)(unsafe.Pointer(&x.Program))
	hxfe8267c.Data = uintptr(unsafe.Pointer(x.ref1497cae7.program))
	hxfe8267c.Cap = 0x7fffffff
	// hxfe8267c.Len = ?

}
