// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 30 Mar 2018 12:26:20 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package slurm provides Go bindings for the Slurm resource manager APIs
*/
package slurm
